# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingWindows(object):
    def setupUi(self, SettingWindows):
        SettingWindows.setObjectName("SettingWindows")
        SettingWindows.resize(856, 532)
        SettingWindows.setWindowModality(Qt.ApplicationModal)
        SettingWindows.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowSystemMenuHint)

        self.centralwidget = QtWidgets.QWidget(SettingWindows)
        self.centralwidget.setObjectName("centralwidget")
        self.settingTab = QtWidgets.QTabWidget(self.centralwidget)
        self.settingTab.setGeometry(QtCore.QRect(30, 50, 801, 381))
        self.settingTab.setObjectName("settingTab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_3.setGeometry(QtCore.QRect(98, 180, 561, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 101, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 180, 81, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(self.tab1)
        self.pushButton.setGeometry(QtCore.QRect(680, 30, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 531, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 90, 561, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 270, 81, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_4.setGeometry(QtCore.QRect(68, 270, 591, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 72, 15))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_2.setGeometry(QtCore.QRect(682, 90, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(120, 120, 61, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 120, 161, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab1)
        self.label_7.setGeometry(QtCore.QRect(380, 120, 41, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_6.setGeometry(QtCore.QRect(430, 120, 161, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_7.setGeometry(QtCore.QRect(430, 210, 161, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 210, 161, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtWidgets.QLabel(self.tab1)
        self.label_8.setGeometry(QtCore.QRect(380, 210, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab1)
        self.label_9.setGeometry(QtCore.QRect(120, 210, 61, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_9.setGeometry(QtCore.QRect(430, 300, 161, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_10 = QtWidgets.QLabel(self.tab1)
        self.label_10.setGeometry(QtCore.QRect(380, 300, 41, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_10.setGeometry(QtCore.QRect(180, 300, 161, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.tab1)
        self.label_11.setGeometry(QtCore.QRect(120, 300, 61, 16))
        self.label_11.setObjectName("label_11")
        self.settingTab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.radioButton = QtWidgets.QRadioButton(self.tab2)
        self.radioButton.setGeometry(QtCore.QRect(80, 70, 115, 19))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab2)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 120, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab2)
        self.radioButton_3.setGeometry(QtCore.QRect(80, 170, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.dateEdit = QtWidgets.QDateEdit(self.tab2)
        self.dateEdit.setGeometry(QtCore.QRect(170, 170, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.settingTab.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_11.setGeometry(QtCore.QRect(240, 50, 301, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_12 = QtWidgets.QLabel(self.tab3)
        self.label_12.setGeometry(QtCore.QRect(90, 50, 141, 16))
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.tab3)
        self.label_14.setGeometry(QtCore.QRect(90, 100, 141, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab3)
        self.label_15.setGeometry(QtCore.QRect(90, 150, 101, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab3)
        self.label_16.setGeometry(QtCore.QRect(90, 200, 101, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab3)
        self.label_17.setGeometry(QtCore.QRect(90, 250, 101, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_12.setGeometry(QtCore.QRect(240, 100, 81, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_13.setGeometry(QtCore.QRect(210, 150, 331, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_14.setGeometry(QtCore.QRect(210, 200, 331, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 250, 331, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.settingTab.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.textEdit = QtWidgets.QTextEdit(self.tab4)
        self.textEdit.setGeometry(QtCore.QRect(50, 100, 681, 191))
        self.textEdit.setObjectName("textEdit")
        self.label_13 = QtWidgets.QLabel(self.tab4)
        self.label_13.setGeometry(QtCore.QRect(30, 30, 351, 51))
        self.label_13.setObjectName("label_13")
        self.settingTab.addTab(self.tab4, "")
        self.Squit = QtWidgets.QPushButton(self.centralwidget)
        self.Squit.setGeometry(QtCore.QRect(820, 10, 21, 21))
        self.Squit.setText("")
        self.Squit.setObjectName("Squit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 16))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 460, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 460, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        SettingWindows.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindows)
        self.settingTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingWindows)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.dragPosition = event.globalPos() - self.frameGeometry().topLeft()
            QApplication.postEvent(self, QEvent(174))
            event.accept()

    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.LeftButton:
            self.move(event.globalPos() - self.dragPosition)
            event.accept()

    def retranslateUi(self, SettingWindows):
        _translate = QtCore.QCoreApplication.translate
        SettingWindows.setWindowTitle(_translate("SettingWindows", "设置"))
        self.label_5.setText(_translate("SettingWindows", "数据读取路径："))
        self.pushButton_5.setText(_translate("SettingWindows", "选择系统"))
        self.pushButton.setText(_translate("SettingWindows", "选择文件"))
        self.label_3.setText(_translate("SettingWindows", "财务系统："))
        self.pushButton_6.setText(_translate("SettingWindows", "选择系统"))
        self.label_4.setText(_translate("SettingWindows", "O32："))
        self.pushButton_2.setText(_translate("SettingWindows", "选择系统"))
        self.label_2.setText(_translate("SettingWindows", "估值系统："))
        self.label_6.setText(_translate("SettingWindows", "用户名："))
        self.label_7.setText(_translate("SettingWindows", "密码："))
        self.label_8.setText(_translate("SettingWindows", "密码："))
        self.label_9.setText(_translate("SettingWindows", "用户名："))
        self.label_10.setText(_translate("SettingWindows", "密码："))
        self.label_11.setText(_translate("SettingWindows", "用户名："))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tab1), _translate("SettingWindows", "路径（必填）"))
        self.radioButton.setText(_translate("SettingWindows", " T 日"))
        self.radioButton_2.setText(_translate("SettingWindows", " T + 1 日"))
        self.radioButton_3.setText(_translate("SettingWindows", " 自定义"))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tab2), _translate("SettingWindows", "制作日期"))
        self.label_12.setText(_translate("SettingWindows", "邮件的服务器地址："))
        self.label_14.setText(_translate("SettingWindows", "邮件的服务器端口："))
        self.label_15.setText(_translate("SettingWindows", "发送邮箱账号："))
        self.label_16.setText(_translate("SettingWindows", "发送邮箱密码："))
        self.label_17.setText(_translate("SettingWindows", "接收邮箱账号："))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tab3), _translate("SettingWindows", "邮件"))
        self.label_13.setText(_translate("SettingWindows", "制作黑名单（以中文字符“、”分割，无需换行）："))
        self.settingTab.setTabText(self.settingTab.indexOf(self.tab4), _translate("SettingWindows", "黑名单"))
        self.label.setText(_translate("SettingWindows", "设置"))
        self.pushButton_3.setText(_translate("SettingWindows", "确 定"))
        self.pushButton_4.setText(_translate("SettingWindows", "取 消"))

        self.Squit.setStyleSheet("QPushButton{border-image: url(image/quit.png)}")

