# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowsmomo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1070, 879)
        font = QtGui.QFont()
        font.setPointSize(12)
        mainWindow.setFont(font)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        mainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowSystemMenuHint)

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(130, 270, 801, 101))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.step1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.step1Label.setText("")
        self.step1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step1Label.setObjectName("step1Label")
        self.verticalLayout_2.addWidget(self.step1Label)
        self.step1Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step1Text.setFont(font)
        self.step1Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step1Text.setObjectName("step1Text")
        self.verticalLayout_2.addWidget(self.step1Text)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.arrows1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.arrows1Label.setText("")
        self.arrows1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows1Label.setObjectName("arrows1Label")
        self.verticalLayout_20.addWidget(self.arrows1Label)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_20.addWidget(self.label_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_20)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.step2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.step2Label.setText("")
        self.step2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step2Label.setObjectName("step2Label")
        self.verticalLayout_3.addWidget(self.step2Label)
        self.step2Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step2Text.setFont(font)
        self.step2Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step2Text.setObjectName("step2Text")
        self.verticalLayout_3.addWidget(self.step2Text)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(130, 370, 801, 81))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.arrows2LongLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.arrows2LongLabel.setText("")
        self.arrows2LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows2LongLabel.setObjectName("arrows2LongLabel")
        self.horizontalLayout_10.addWidget(self.arrows2LongLabel)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(130, 450, 801, 101))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.step3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step3Label.setText("")
        self.step3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step3Label.setObjectName("step3Label")
        self.verticalLayout_4.addWidget(self.step3Label)
        self.step3Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step3Text.setFont(font)
        self.step3Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step3Text.setObjectName("step3Text")
        self.verticalLayout_4.addWidget(self.step3Text)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.arrows3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows3Label.setText("")
        self.arrows3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows3Label.setObjectName("arrows3Label")
        self.verticalLayout_18.addWidget(self.arrows3Label)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        self.horizontalLayout_11.addLayout(self.verticalLayout_18)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.step4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step4Label.setText("")
        self.step4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step4Label.setObjectName("step4Label")
        self.verticalLayout_5.addWidget(self.step4Label)
        self.step4Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step4Text.setFont(font)
        self.step4Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step4Text.setObjectName("step4Text")
        self.verticalLayout_5.addWidget(self.step4Text)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.arrows4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows4Label.setText("")
        self.arrows4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows4Label.setObjectName("arrows4Label")
        self.verticalLayout_19.addWidget(self.arrows4Label)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_19.addWidget(self.label_5)
        self.horizontalLayout_11.addLayout(self.verticalLayout_19)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.step5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step5Label.setText("")
        self.step5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step5Label.setObjectName("step5Label")
        self.verticalLayout_6.addWidget(self.step5Label)
        self.step5Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step5Text.setFont(font)
        self.step5Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step5Text.setObjectName("step5Text")
        self.verticalLayout_6.addWidget(self.step5Text)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.arrows5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows5Label.setText("")
        self.arrows5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows5Label.setObjectName("arrows5Label")
        self.verticalLayout_21.addWidget(self.arrows5Label)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_21.addWidget(self.label_7)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.step6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step6Label.setText("")
        self.step6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step6Label.setObjectName("step6Label")
        self.verticalLayout_7.addWidget(self.step6Label)
        self.step6Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step6Text.setFont(font)
        self.step6Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step6Text.setObjectName("step6Text")
        self.verticalLayout_7.addWidget(self.step6Text)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.arrows6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows6Label.setText("")
        self.arrows6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows6Label.setObjectName("arrows6Label")
        self.verticalLayout_22.addWidget(self.arrows6Label)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_22.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.step7Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step7Label.setText("")
        self.step7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step7Label.setObjectName("step7Label")
        self.verticalLayout_8.addWidget(self.step7Label)
        self.step7Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step7Text.setFont(font)
        self.step7Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step7Text.setObjectName("step7Text")
        self.verticalLayout_8.addWidget(self.step7Text)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(142, 90, 380, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.setTime = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.setTime.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.setTime.setFont(font)
        self.setTime.setObjectName("setTime")
        self.verticalLayout.addWidget(self.setTime)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.startTimeEdit = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_3)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.horizontalLayout_3.addWidget(self.startTimeEdit)
        self.timeLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.timeLabel2.setObjectName("timeLabel2")
        self.horizontalLayout_3.addWidget(self.timeLabel2)
        self.endTimeEdit = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_3)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.horizontalLayout_3.addWidget(self.endTimeEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(550, 90, 361, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.PauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout.addWidget(self.PauseButton)
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.workLabel = QtWidgets.QLabel(self.centralwidget)
        self.workLabel.setGeometry(QtCore.QRect(420, 210, 231, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.workLabel.setFont(font)
        self.workLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.workLabel.setObjectName("workLabel")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(130, 630, 801, 101))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.step8Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step8Label.setText("")
        self.step8Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step8Label.setObjectName("step8Label")
        self.verticalLayout_9.addWidget(self.step8Label)
        self.step8Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step8Text.setFont(font)
        self.step8Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step8Text.setObjectName("step8Text")
        self.verticalLayout_9.addWidget(self.step8Text)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.arrows8Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows8Label.setText("")
        self.arrows8Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows8Label.setObjectName("arrows8Label")
        self.verticalLayout_13.addWidget(self.arrows8Label)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.step9Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step9Label.setText("")
        self.step9Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step9Label.setObjectName("step9Label")
        self.verticalLayout_10.addWidget(self.step9Label)
        self.step9Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step9Text.setFont(font)
        self.step9Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step9Text.setObjectName("step9Text")
        self.verticalLayout_10.addWidget(self.step9Text)
        self.horizontalLayout_13.addLayout(self.verticalLayout_10)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.arrows9Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows9Label.setText("")
        self.arrows9Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows9Label.setObjectName("arrows9Label")
        self.verticalLayout_14.addWidget(self.arrows9Label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.step10Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step10Label.setText("")
        self.step10Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step10Label.setObjectName("step10Label")
        self.verticalLayout_11.addWidget(self.step10Label)
        self.step10Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step10Text.setFont(font)
        self.step10Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step10Text.setObjectName("step10Text")
        self.verticalLayout_11.addWidget(self.step10Text)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.arrows10Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows10Label.setText("")
        self.arrows10Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows10Label.setObjectName("arrows10Label")
        self.verticalLayout_16.addWidget(self.arrows10Label)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_16.addWidget(self.label_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_16)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.step11Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step11Label.setText("")
        self.step11Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step11Label.setObjectName("step11Label")
        self.verticalLayout_12.addWidget(self.step11Label)
        self.step11Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.step11Text.setFont(font)
        self.step11Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step11Text.setObjectName("step11Text")
        self.verticalLayout_12.addWidget(self.step11Text)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(130, 730, 801, 61))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.arrows11LongLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.arrows11LongLabel.setText("")
        self.arrows11LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows11LongLabel.setObjectName("arrows11LongLabel")
        self.horizontalLayout_14.addWidget(self.arrows11LongLabel)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(129, 549, 801, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.arrows7LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.arrows7LongLabel.setText("")
        self.arrows7LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows7LongLabel.setObjectName("arrows7LongLabel")
        self.verticalLayout_17.addWidget(self.arrows7LongLabel)
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(20, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.icon.setFont(font)
        self.icon.setObjectName("icon")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(980, 10, 21, 21))
        self.setting.setText("")
        self.setting.setIconSize(QtCore.QSize(30, 30))
        self.setting.setObjectName("setting")
        self.min = QtWidgets.QPushButton(self.centralwidget)
        self.min.setGeometry(QtCore.QRect(1010, 10, 21, 21))
        self.min.setText("")
        self.min.setIconSize(QtCore.QSize(25, 25))
        self.min.setObjectName("min")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(1040, 10, 21, 21))
        self.quit.setText("")
        self.quit.setObjectName("quit")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionguanbi = QtWidgets.QAction(mainWindow)
        self.actionguanbi.setObjectName("actionguanbi")
        self.actiontianjiaheimingdan = QtWidgets.QAction(mainWindow)
        self.actiontianjiaheimingdan.setObjectName("actiontianjiaheimingdan")
        self.actiontianjia = QtWidgets.QAction(mainWindow)
        self.actiontianjia.setObjectName("actiontianjia")
        self.actionmm = QtWidgets.QAction(mainWindow)
        self.actionmm.setObjectName("actionmm")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.dragPosition = event.globalPos() - self.frameGeometry().topLeft()
            QApplication.postEvent(self, QEvent(174))
            event.accept()

    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.LeftButton:
            self.move(event.globalPos() - self.dragPosition)
            event.accept()

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "小智机器人"))
        self.step1Text.setText(_translate("mainWindow", "开始进程"))
        self.step2Text.setText(_translate("mainWindow", "读取产品参数维护表"))
        self.step3Text.setText(_translate("mainWindow", "启动"))
        self.step4Text.setText(_translate("mainWindow", "文件导入"))
        self.step5Text.setText(_translate("mainWindow", "制作凭证"))
        self.step6Text.setText(_translate("mainWindow", "生成估值表"))
        self.step7Text.setText(_translate("mainWindow", "关闭"))
        self.setTime.setText(_translate("mainWindow", "设置自动运行时间："))
        self.timeLabel2.setText(_translate("mainWindow", "-"))
        self.startButton.setText(_translate("mainWindow", "执行"))
        self.PauseButton.setText(_translate("mainWindow", "暂停"))
        self.quitButton.setText(_translate("mainWindow", "终止"))
        self.workLabel.setText(_translate("mainWindow", "工作进程展示"))
        self.step8Text.setText(_translate("mainWindow", "启动"))
        self.step9Text.setText(_translate("mainWindow", "对账结果管理"))
        self.step10Text.setText(_translate("mainWindow", "处理并发送对账结果"))
        self.step11Text.setText(_translate("mainWindow", "关闭"))
        self.icon.setText(_translate("mainWindow", "小智机器人"))
        self.actionguanbi.setText(_translate("mainWindow", "关闭"))
        self.actiontianjiaheimingdan.setText(_translate("mainWindow", "添加黑名单"))
        self.actiontianjia.setText(_translate("mainWindow", "设置做账日期"))
        self.actionmm.setText(_translate("mainWindow", "邮件接口"))



        scale = 1.5
        arwScale = 0.6

        self.setting.setStyleSheet("QPushButton{border-image: url(image/setting.png)}")
        self.min.setStyleSheet("QPushButton{border-image: url(image/min.png)}")
        self.quit.setStyleSheet("QPushButton{border-image: url(image/quit.png)}")

        frame = QImage('image/startL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step1Label.width(), self.step1Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step1Label.setPixmap(pix)

        frame = QImage('image/readL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step2Label.width(), self.step2Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step2Label.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step3Label.width(), self.step3Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step3Label.setPixmap(pix)

        frame = QImage('image/loadL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step4Label.width(), self.step4Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step4Label.setPixmap(pix)

        frame = QImage('image/makeKeyL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step5Label.width(), self.step5Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step5Label.setPixmap(pix)

        frame = QImage('image/productL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step6Label.width(), self.step6Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step6Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step7Label.width(), self.step7Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step7Label.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step8Label.width(), self.step8Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step8Label.setPixmap(pix)

        frame = QImage('image/mngL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step9Label.width(), self.step9Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step9Label.setPixmap(pix)

        frame = QImage('image/sendL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step10Label.width(), self.step10Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step10Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step11Label.width(), self.step11Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step11Label.setPixmap(pix)

        frame = QImage('image/arrowsD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows1Label.width(), self.arrows1Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows1Label.setPixmap(pix)

        frame = QImage('image/arrowsLongL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows2LongLabel.width(), self.arrows2LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 2), int(lbh * 2)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows2LongLabel.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows3Label.width(), self.arrows3Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows3Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows4Label.width(), self.arrows4Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows4Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows5Label.width(), self.arrows5Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows5Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows6Label.width(), self.arrows6Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows6Label.setPixmap(pix)

        frame = QImage('image/arrowsLongL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows7LongLabel.width(), self.arrows7LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 1.9), int(lbh * 1.9)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows7LongLabel.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows8Label.width(), self.arrows8Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows8Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows9Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows9Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows10Label.width(), self.arrows10Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows10Label.setPixmap(pix)

        frame = QImage('image/arrowsLong2L.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows11LongLabel.width(), self.arrows11LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 1.3), int(lbh * 1.3)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows11LongLabel.setPixmap(pix)

