# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowsmomo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1070, 879)
        font = QtGui.QFont()
        font.setPointSize(12)
        mainWindow.setFont(font)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        mainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowSystemMenuHint)

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(142, 60, 380, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.setTime = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.setTime.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.setTime.setFont(font)
        self.setTime.setObjectName("setTime")
        self.verticalLayout.addWidget(self.setTime)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.startTimeEdit = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_3)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.horizontalLayout_3.addWidget(self.startTimeEdit)
        self.timeLabel2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.timeLabel2.setObjectName("timeLabel2")
        self.horizontalLayout_3.addWidget(self.timeLabel2)
        self.endTimeEdit = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_3)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.horizontalLayout_3.addWidget(self.endTimeEdit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(550, 60, 361, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.PauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout.addWidget(self.PauseButton)
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.workLabel = QtWidgets.QLabel(self.centralwidget)
        self.workLabel.setGeometry(QtCore.QRect(420, 170, 231, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.workLabel.setFont(font)
        self.workLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.workLabel.setObjectName("workLabel")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(20, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.icon.setFont(font)
        self.icon.setObjectName("icon")
        self.setting = QtWidgets.QPushButton(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(980, 10, 21, 21))
        self.setting.setText("")
        self.setting.setIconSize(QtCore.QSize(30, 30))
        self.setting.setObjectName("setting")
        self.min = QtWidgets.QPushButton(self.centralwidget)
        self.min.setGeometry(QtCore.QRect(1010, 10, 21, 21))
        self.min.setText("")
        self.min.setIconSize(QtCore.QSize(25, 25))
        self.min.setObjectName("min")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(1040, 10, 21, 21))
        self.quit.setText("")
        self.quit.setObjectName("quit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 200, 961, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(50, 391, 841, 101))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.step8Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step8Label.setText("")
        self.step8Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step8Label.setObjectName("step8Label")
        self.verticalLayout_15.addWidget(self.step8Label)
        self.step8Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step8Text.setFont(font)
        self.step8Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step8Text.setObjectName("step8Text")
        self.verticalLayout_15.addWidget(self.step8Text)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.arrows8Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows8Label.setText("")
        self.arrows8Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows8Label.setObjectName("arrows8Label")
        self.verticalLayout_23.addWidget(self.arrows8Label)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_23.addWidget(self.label_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.step9Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step9Label.setText("")
        self.step9Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step9Label.setObjectName("step9Label")
        self.verticalLayout_24.addWidget(self.step9Label)
        self.step9Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step9Text.setFont(font)
        self.step9Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step9Text.setObjectName("step9Text")
        self.verticalLayout_24.addWidget(self.step9Text)
        self.horizontalLayout_15.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.arrows9Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows9Label.setText("")
        self.arrows9Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows9Label.setObjectName("arrows9Label")
        self.verticalLayout_25.addWidget(self.arrows9Label)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_25.addWidget(self.label_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.step10Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step10Label.setText("")
        self.step10Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step10Label.setObjectName("step10Label")
        self.verticalLayout_26.addWidget(self.step10Label)
        self.step10Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step10Text.setFont(font)
        self.step10Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step10Text.setObjectName("step10Text")
        self.verticalLayout_26.addWidget(self.step10Text)
        self.horizontalLayout_15.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.arrows10Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.arrows10Label.setText("")
        self.arrows10Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows10Label.setObjectName("arrows10Label")
        self.verticalLayout_27.addWidget(self.arrows10Label)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_27.addWidget(self.label_11)
        self.horizontalLayout_15.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.step11Label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.step11Label.setText("")
        self.step11Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step11Label.setObjectName("step11Label")
        self.verticalLayout_28.addWidget(self.step11Label)
        self.step11Text = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step11Text.setFont(font)
        self.step11Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step11Text.setObjectName("step11Text")
        self.verticalLayout_28.addWidget(self.step11Text)
        self.horizontalLayout_15.addLayout(self.verticalLayout_28)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 31, 841, 101))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.step1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.step1Label.setText("")
        self.step1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step1Label.setObjectName("step1Label")
        self.verticalLayout_29.addWidget(self.step1Label)
        self.step1Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step1Text.setFont(font)
        self.step1Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step1Text.setObjectName("step1Text")
        self.verticalLayout_29.addWidget(self.step1Text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.arrows1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.arrows1Label.setText("")
        self.arrows1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows1Label.setObjectName("arrows1Label")
        self.verticalLayout_30.addWidget(self.arrows1Label)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_30.addWidget(self.label_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.step2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.step2Label.setText("")
        self.step2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step2Label.setObjectName("step2Label")
        self.verticalLayout_31.addWidget(self.step2Label)
        self.step2Text = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step2Text.setFont(font)
        self.step2Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step2Text.setObjectName("step2Text")
        self.verticalLayout_31.addWidget(self.step2Text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_31)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(50, 310, 841, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.arrows7LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.arrows7LongLabel.setText("")
        self.arrows7LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows7LongLabel.setObjectName("arrows7LongLabel")
        self.verticalLayout_32.addWidget(self.arrows7LongLabel)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 211, 841, 101))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.step3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step3Label.setText("")
        self.step3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step3Label.setObjectName("step3Label")
        self.verticalLayout_33.addWidget(self.step3Label)
        self.step3Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step3Text.setFont(font)
        self.step3Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step3Text.setObjectName("step3Text")
        self.verticalLayout_33.addWidget(self.step3Text)
        self.horizontalLayout_12.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.arrows3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows3Label.setText("")
        self.arrows3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows3Label.setObjectName("arrows3Label")
        self.verticalLayout_34.addWidget(self.arrows3Label)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_34.addWidget(self.label_13)
        self.horizontalLayout_12.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.step4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step4Label.setText("")
        self.step4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step4Label.setObjectName("step4Label")
        self.verticalLayout_35.addWidget(self.step4Label)
        self.step4Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step4Text.setFont(font)
        self.step4Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step4Text.setObjectName("step4Text")
        self.verticalLayout_35.addWidget(self.step4Text)
        self.horizontalLayout_12.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.arrows4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows4Label.setText("")
        self.arrows4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows4Label.setObjectName("arrows4Label")
        self.verticalLayout_36.addWidget(self.arrows4Label)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_36.addWidget(self.label_14)
        self.horizontalLayout_12.addLayout(self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.step5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step5Label.setText("")
        self.step5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step5Label.setObjectName("step5Label")
        self.verticalLayout_37.addWidget(self.step5Label)
        self.step5Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step5Text.setFont(font)
        self.step5Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step5Text.setObjectName("step5Text")
        self.verticalLayout_37.addWidget(self.step5Text)
        self.horizontalLayout_12.addLayout(self.verticalLayout_37)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.arrows5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows5Label.setText("")
        self.arrows5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows5Label.setObjectName("arrows5Label")
        self.verticalLayout_38.addWidget(self.arrows5Label)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_38.addWidget(self.label_15)
        self.horizontalLayout_12.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.step6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step6Label.setText("")
        self.step6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step6Label.setObjectName("step6Label")
        self.verticalLayout_39.addWidget(self.step6Label)
        self.step6Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.step6Text.setFont(font)
        self.step6Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step6Text.setObjectName("step6Text")
        self.verticalLayout_39.addWidget(self.step6Text)
        self.horizontalLayout_12.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.arrows6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.arrows6Label.setText("")
        self.arrows6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows6Label.setObjectName("arrows6Label")
        self.verticalLayout_40.addWidget(self.arrows6Label)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_40.addWidget(self.label_16)
        self.horizontalLayout_12.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.step7Label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.step7Label.setText("")
        self.step7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.step7Label.setObjectName("step7Label")
        self.verticalLayout_41.addWidget(self.step7Label)
        self.step7Text = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.step7Text.setFont(font)
        self.step7Text.setAlignment(QtCore.Qt.AlignCenter)
        self.step7Text.setObjectName("step7Text")
        self.verticalLayout_41.addWidget(self.step7Text)
        self.horizontalLayout_12.addLayout(self.verticalLayout_41)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 131, 841, 81))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.arrows2LongLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.arrows2LongLabel.setText("")
        self.arrows2LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows2LongLabel.setObjectName("arrows2LongLabel")
        self.horizontalLayout_17.addWidget(self.arrows2LongLabel)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 490, 841, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.arrows11LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.arrows11LongLabel.setText("")
        self.arrows11LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows11LongLabel.setObjectName("arrows11LongLabel")
        self.verticalLayout_42.addWidget(self.arrows11LongLabel)
        self.arrows11Text = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.arrows11Text.setFont(font)
        self.arrows11Text.setText("")
        self.arrows11Text.setAlignment(QtCore.Qt.AlignCenter)
        self.arrows11Text.setObjectName("arrows11Text")
        self.verticalLayout_42.addWidget(self.arrows11Text)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(49, 180, 841, 81))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.T2arrows4LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.T2arrows4LongLabel.setText("")
        self.T2arrows4LongLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows4LongLabel.setObjectName("T2arrows4LongLabel")
        self.verticalLayout_43.addWidget(self.T2arrows4LongLabel)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 261, 841, 101))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.T2step5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2step5Label.setText("")
        self.T2step5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step5Label.setObjectName("T2step5Label")
        self.verticalLayout_16.addWidget(self.T2step5Label)
        self.T2step5Text = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step5Text.setFont(font)
        self.T2step5Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step5Text.setObjectName("T2step5Text")
        self.verticalLayout_16.addWidget(self.T2step5Text)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.T2arrows5Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2arrows5Label.setText("")
        self.T2arrows5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows5Label.setObjectName("T2arrows5Label")
        self.verticalLayout_44.addWidget(self.T2arrows5Label)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_44.addWidget(self.label_17)
        self.horizontalLayout_16.addLayout(self.verticalLayout_44)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.T2step6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2step6Label.setText("")
        self.T2step6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step6Label.setObjectName("T2step6Label")
        self.verticalLayout_45.addWidget(self.T2step6Label)
        self.T2step6Text = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step6Text.setFont(font)
        self.T2step6Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step6Text.setObjectName("T2step6Text")
        self.verticalLayout_45.addWidget(self.T2step6Text)
        self.horizontalLayout_16.addLayout(self.verticalLayout_45)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.T2arrows6Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2arrows6Label.setText("")
        self.T2arrows6Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows6Label.setObjectName("T2arrows6Label")
        self.verticalLayout_46.addWidget(self.T2arrows6Label)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_46.addWidget(self.label_18)
        self.horizontalLayout_16.addLayout(self.verticalLayout_46)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.T2step7Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2step7Label.setText("")
        self.T2step7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step7Label.setObjectName("T2step7Label")
        self.verticalLayout_47.addWidget(self.T2step7Label)
        self.T2step7Text = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step7Text.setFont(font)
        self.T2step7Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step7Text.setObjectName("T2step7Text")
        self.verticalLayout_47.addWidget(self.T2step7Text)
        self.horizontalLayout_16.addLayout(self.verticalLayout_47)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.T2arrows7Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2arrows7Label.setText("")
        self.T2arrows7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows7Label.setObjectName("T2arrows7Label")
        self.verticalLayout_48.addWidget(self.T2arrows7Label)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_48.addWidget(self.label_19)
        self.horizontalLayout_16.addLayout(self.verticalLayout_48)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.T2step8Label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.T2step8Label.setText("")
        self.T2step8Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step8Label.setObjectName("T2step8Label")
        self.verticalLayout_49.addWidget(self.T2step8Label)
        self.T2step8Text = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step8Text.setFont(font)
        self.T2step8Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step8Text.setObjectName("T2step8Text")
        self.verticalLayout_49.addWidget(self.T2step8Text)
        self.horizontalLayout_16.addLayout(self.verticalLayout_49)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(50, 82, 841, 101))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.T2step1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2step1Label.setText("")
        self.T2step1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step1Label.setObjectName("T2step1Label")
        self.verticalLayout_17.addWidget(self.T2step1Label)
        self.T2step1Text = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step1Text.setFont(font)
        self.T2step1Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step1Text.setObjectName("T2step1Text")
        self.verticalLayout_17.addWidget(self.T2step1Text)
        self.horizontalLayout_18.addLayout(self.verticalLayout_17)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.T2arrows1Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2arrows1Label.setText("")
        self.T2arrows1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows1Label.setObjectName("T2arrows1Label")
        self.verticalLayout_50.addWidget(self.T2arrows1Label)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_50.addWidget(self.label_20)
        self.horizontalLayout_18.addLayout(self.verticalLayout_50)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.T2step2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2step2Label.setText("")
        self.T2step2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step2Label.setObjectName("T2step2Label")
        self.verticalLayout_51.addWidget(self.T2step2Label)
        self.T2step2Text = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step2Text.setFont(font)
        self.T2step2Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step2Text.setObjectName("T2step2Text")
        self.verticalLayout_51.addWidget(self.T2step2Text)
        self.horizontalLayout_18.addLayout(self.verticalLayout_51)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.T2arrows2Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2arrows2Label.setText("")
        self.T2arrows2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows2Label.setObjectName("T2arrows2Label")
        self.verticalLayout_52.addWidget(self.T2arrows2Label)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_52.addWidget(self.label_21)
        self.horizontalLayout_18.addLayout(self.verticalLayout_52)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.T2step3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2step3Label.setText("")
        self.T2step3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step3Label.setObjectName("T2step3Label")
        self.verticalLayout_53.addWidget(self.T2step3Label)
        self.T2step3Text = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step3Text.setFont(font)
        self.T2step3Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step3Text.setObjectName("T2step3Text")
        self.verticalLayout_53.addWidget(self.T2step3Text)
        self.horizontalLayout_18.addLayout(self.verticalLayout_53)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.T2arrows3Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2arrows3Label.setText("")
        self.T2arrows3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2arrows3Label.setObjectName("T2arrows3Label")
        self.verticalLayout_54.addWidget(self.T2arrows3Label)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_54.addWidget(self.label_22)
        self.horizontalLayout_18.addLayout(self.verticalLayout_54)
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.T2step4Label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.T2step4Label.setText("")
        self.T2step4Label.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step4Label.setObjectName("T2step4Label")
        self.verticalLayout_55.addWidget(self.T2step4Label)
        self.T2step4Text = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.T2step4Text.setFont(font)
        self.T2step4Text.setAlignment(QtCore.Qt.AlignCenter)
        self.T2step4Text.setObjectName("T2step4Text")
        self.verticalLayout_55.addWidget(self.T2step4Text)
        self.horizontalLayout_18.addLayout(self.verticalLayout_55)
        self.tabWidget.addTab(self.tab_2, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionguanbi = QtWidgets.QAction(mainWindow)
        self.actionguanbi.setObjectName("actionguanbi")
        self.actiontianjiaheimingdan = QtWidgets.QAction(mainWindow)
        self.actiontianjiaheimingdan.setObjectName("actiontianjiaheimingdan")
        self.actiontianjia = QtWidgets.QAction(mainWindow)
        self.actiontianjia.setObjectName("actiontianjia")
        self.actionmm = QtWidgets.QAction(mainWindow)
        self.actionmm.setObjectName("actionmm")

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.dragPosition = event.globalPos() - self.frameGeometry().topLeft()
            QApplication.postEvent(self, QEvent(174))
            event.accept()

    def mouseMoveEvent(self, event):
        if event.buttons() == Qt.LeftButton:
            self.move(event.globalPos() - self.dragPosition)
            event.accept()

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "小智机器人"))
        self.setTime.setText(_translate("mainWindow", "设置自动运行时间："))
        self.timeLabel2.setText(_translate("mainWindow", "-"))
        self.startButton.setText(_translate("mainWindow", "执行"))
        self.PauseButton.setText(_translate("mainWindow", "暂停"))
        self.quitButton.setText(_translate("mainWindow", "终止"))
        self.workLabel.setText(_translate("mainWindow", "工作流程展示"))
        self.icon.setText(_translate("mainWindow", "小智机器人"))
        self.step8Text.setText(_translate("mainWindow", "启动报表系统"))
        self.step9Text.setText(_translate("mainWindow", "电子对账查询"))
        self.step10Text.setText(_translate("mainWindow", "处理并发送对账结果"))
        self.step11Text.setText(_translate("mainWindow", "关闭并等待托管行"))
        self.step1Text.setText(_translate("mainWindow", "进行环境检查"))
        self.step2Text.setText(_translate("mainWindow", "读取产品参数维护表"))
        self.step3Text.setText(_translate("mainWindow", "启动估值系统"))
        self.step4Text.setText(_translate("mainWindow", "文件导入"))
        self.step5Text.setText(_translate("mainWindow", "制作凭证"))
        self.step6Text.setText(_translate("mainWindow", "生成估值表"))
        self.step7Text.setText(_translate("mainWindow", "关闭并等待托管行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "做账流程"))
        self.T2step5Text.setText(_translate("mainWindow", "启动O32"))
        self.T2step6Text.setText(_translate("mainWindow", "导出基金资产表"))
        self.T2step7Text.setText(_translate("mainWindow", "净值核对"))
        self.T2step8Text.setText(_translate("mainWindow", "关闭"))
        self.T2step1Text.setText(_translate("mainWindow", "启动报表系统"))
        self.T2step2Text.setText(_translate("mainWindow", "导出资产情况统计表"))
        self.T2step3Text.setText(_translate("mainWindow", "导出现金头寸预测汇总表"))
        self.T2step4Text.setText(_translate("mainWindow", "关闭"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "核对流程"))
        self.actionguanbi.setText(_translate("mainWindow", "关闭"))
        self.actiontianjiaheimingdan.setText(_translate("mainWindow", "添加黑名单"))
        self.actiontianjia.setText(_translate("mainWindow", "设置做账日期"))
        self.actionmm.setText(_translate("mainWindow", "邮件接口"))

        scale = 1.5
        arwScale = 0.6

        self.setting.setStyleSheet("QPushButton{border-image: url(image/setting.png)}")
        self.min.setStyleSheet("QPushButton{border-image: url(image/min.png)}")
        self.quit.setStyleSheet("QPushButton{border-image: url(image/quit.png)}")

        frame = QImage('image/startL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step1Label.width(), self.step1Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step1Label.setPixmap(pix)

        frame = QImage('image/readL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step2Label.width(), self.step2Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step2Label.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step3Label.width(), self.step3Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step3Label.setPixmap(pix)

        frame = QImage('image/loadL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step4Label.width(), self.step4Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step4Label.setPixmap(pix)

        frame = QImage('image/makeKeyL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step5Label.width(), self.step5Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step5Label.setPixmap(pix)

        frame = QImage('image/productL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step6Label.width(), self.step6Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step6Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step7Label.width(), self.step7Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step7Label.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step8Label.width(), self.step8Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step8Label.setPixmap(pix)

        frame = QImage('image/mngL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step9Label.width(), self.step9Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step9Label.setPixmap(pix)

        frame = QImage('image/sendL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step10Label.width(), self.step10Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step10Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.step11Label.width(), self.step11Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.step11Label.setPixmap(pix)

        frame = QImage('image/arrowsD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows1Label.width(), self.arrows1Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows1Label.setPixmap(pix)

        frame = QImage('image/arrowsLongL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows2LongLabel.width(), self.arrows2LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 2), int(lbh * 2)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows2LongLabel.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows3Label.width(), self.arrows3Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows3Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows4Label.width(), self.arrows4Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows4Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows5Label.width(), self.arrows5Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows5Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows6Label.width(), self.arrows6Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows6Label.setPixmap(pix)

        frame = QImage('image/arrowsLongL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows7LongLabel.width(), self.arrows7LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 1.9), int(lbh * 1.9)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows7LongLabel.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows8Label.width(), self.arrows8Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows8Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows9Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows9Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows10Label.width(), self.arrows10Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows10Label.setPixmap(pix)

        frame = QImage('image/arrowsLong2L.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.arrows11LongLabel.width(), self.arrows11LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 1.3), int(lbh * 1.3)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.arrows11LongLabel.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step1Label.width(), self.step8Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step1Label.setPixmap(pix)

        frame = QImage('image/productL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step2Label.width(), self.step6Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step2Label.setPixmap(pix)

        frame = QImage('image/productL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step3Label.width(), self.step6Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step3Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step4Label.width(), self.step11Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step4Label.setPixmap(pix)

        frame = QImage('image/setupL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step5Label.width(), self.step8Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step5Label.setPixmap(pix)

        frame = QImage('image/productL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step6Label.width(), self.step6Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step6Label.setPixmap(pix)

        frame = QImage('image/mngL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step7Label.width(), self.step9Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step7Label.setPixmap(pix)

        frame = QImage('image/quitL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2step8Label.width(), self.step11Label.height()
        rew, reh = int((lbh / imgh) * imgw * scale), int(lbh * scale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2step8Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows1Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows1Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows2Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows2Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows3Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows3Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows5Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows5Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows6Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows6Label.setPixmap(pix)

        frame = QImage('image/arrowsShotD.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows7Label.width(), self.arrows9Label.height()
        rew, reh = int((lbh / imgh) * imgw * arwScale), int(lbh * arwScale)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows7Label.setPixmap(pix)

        frame = QImage('image/arrowsLongL.png')
        imgw, imgh = frame.width(), frame.height()
        lbw, lbh = self.T2arrows4LongLabel.width(), self.arrows2LongLabel.height()
        rew, reh = int((lbh / imgh) * imgw * 2), int(lbh * 2)
        size = QtCore.QSize(rew, reh)
        pix = QPixmap.fromImage(frame.scaled(size, QtCore.Qt.IgnoreAspectRatio))
        self.T2arrows4LongLabel.setPixmap(pix)

